<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-11-18">

<title>Fairness-Aware Machine Learning with  – Applied Data Science for Cities</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-f3c2ea88cadbcfb37ba28ffa2c97cfc1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Applied Data Science for Cities</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../labs/index.html"> 
<span class="menu-text">Labs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../resource.html"> 
<span class="menu-text">Resource</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#data-and-disputes" id="toc-data-and-disputes" class="nav-link active" data-scroll-target="#data-and-disputes">Data and Disputes</a>
  <ul class="collapse">
  <li><a href="#evaluate-compas" id="toc-evaluate-compas" class="nav-link" data-scroll-target="#evaluate-compas">Evaluate COMPAS</a></li>
  <li><a href="#model-accuracy" id="toc-model-accuracy" class="nav-link" data-scroll-target="#model-accuracy"><strong>Model Accuracy</strong></a></li>
  <li><a href="#confusion-matrix" id="toc-confusion-matrix" class="nav-link" data-scroll-target="#confusion-matrix">Confusion Matrix</a></li>
  <li><a href="#breaking-it-down-by-racial-groups" id="toc-breaking-it-down-by-racial-groups" class="nav-link" data-scroll-target="#breaking-it-down-by-racial-groups">Breaking it down by racial groups</a></li>
  </ul></li>
  <li><a href="#logistic-classification-model" id="toc-logistic-classification-model" class="nav-link" data-scroll-target="#logistic-classification-model">Logistic classification model</a>
  <ul class="collapse">
  <li><a href="#variable-selection-notes" id="toc-variable-selection-notes" class="nav-link" data-scroll-target="#variable-selection-notes"><strong>Variable selection notes</strong></a></li>
  <li><a href="#model-building" id="toc-model-building" class="nav-link" data-scroll-target="#model-building"><strong>Model Building</strong></a></li>
  <li><a href="#our-result" id="toc-our-result" class="nav-link" data-scroll-target="#our-result"><strong>Our Result</strong></a></li>
  </ul></li>
  <li><a href="#adjust-classification-thresholds" id="toc-adjust-classification-thresholds" class="nav-link" data-scroll-target="#adjust-classification-thresholds">Adjust Classification Thresholds</a></li>
  <li><a href="#lab-report" id="toc-lab-report" class="nav-link" data-scroll-target="#lab-report">Lab Report</a>
  <ul class="collapse">
  <li><a href="#your-task" id="toc-your-task" class="nav-link" data-scroll-target="#your-task"><strong>Your Task</strong></a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fairness-Aware Machine Learning with <img src="../img/Rlogo.png" class="img-fluid" width="60"></h1>
<p class="subtitle lead"><span style="color:#2C3E50">11.118/11.218 Applied Data Science for Cities</span></p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 18, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mlr3fairness)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="data-and-disputes" class="level1">
<h1>Data and Disputes</h1>
<p>Today we will explore the COMPAS (Correctional Offender Management Profiling for Alternative Sanctions) model. It was a popular commercial algorithm used by judges and parole officers for scoring criminal defendant’s likelihood of reoffending (recidivism). <a href="https://www.propublica.org/article/how-we-analyzed-the-compas-recidivism-algorithm">ProPublica</a> has shown that the algorithm is biased in favor of white defendants, and against black inmates, based on a two-year follow-up study (i.e who actually committed crimes or violent crimes after 2 years). The pattern of mistakes across racial groups in this dataset is notable.</p>
<p>This dataset is frequently used to study machine learning bias and is now readily available through <a href="https://search.r-project.org/CRAN/refmans/mlr3fairness/html/compas.html"><code>mlr3fairness</code></a> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"compas"</span>, <span class="at">package =</span> <span class="st">"mlr3fairness"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If you check out <code>?mlr3fairness::compas</code>, you will see its documentation including variable explanations and data processing notes. The data includes basic demographics (<code>age</code>, <code>race</code>, <code>sex</code>), and a few variables about prior offense history, such as charge degree (<code>c_charge_degree</code>: F for Felony, M for Misdemeanor), and <code>length_of_stay</code>.</p>
<p>The <code>decile_score</code> column is the COMPAS model’s estimated risk of recidivism (1–10). The <code>score_text</code> column puts these into text categories: Low (1–4), Medium (5–7), and High (8–10) risk.</p>
<p>Then there is the <code>two_year_recid</code> column. This is based on Propublica’s follow-up. It’s a binary variable indicate whether defendant was actually rearrested (1) and not rearrested (0) within two years.</p>
<section id="evaluate-compas" class="level2">
<h2 class="anchored" data-anchor-id="evaluate-compas">Evaluate COMPAS</h2>
<p>How did COMPAS come up with the <code>decile_score</code> is not known (a proprietary algorithm), but we can treat these scores as a “predicted label”, and the <code>two_year_recid</code> as the “actual label” to evaluate this COMPAS’s performance.</p>
<p>To clarify our analysis, we’ll create two new columns. The first, <strong>predicted</strong>, will be “Yes” if <code>decile_score</code> is greater than 5, and “No” if otherwise. The second, <strong>actual</strong>, will be “Yes” if <code>two_year_recid</code> is 1, and “No” if it is 0.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>compas <span class="ot">&lt;-</span> compas <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">predicted =</span> <span class="fu">case_when</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>      decile_score <span class="sc">&gt;</span> <span class="dv">5</span>  <span class="sc">~</span> <span class="st">"yes"</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>      decile_score <span class="sc">&lt;=</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">"no"</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">actual =</span> <span class="fu">factor</span>(</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>      two_year_recid,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"no"</span>, <span class="st">"yes"</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="model-accuracy" class="level2">
<h2 class="anchored" data-anchor-id="model-accuracy"><strong>Model Accuracy</strong></h2>
<p>How well does COMPAS predict reoffending? One way to measure it is by checking the model’s accuracy. Since this is a classification problem with “Yes” or “No” outcomes, accuracy is defined as the proportion of <strong>correct predictions</strong>: both when the model predicts reoffending and the person does reoffend, and when it predicts no reoffending and the person does not.</p>
<p>In other words, accuracy tells us how often the model is correct overall.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>correct_predictions <span class="ot">&lt;-</span> compas <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    (predicted <span class="sc">==</span> <span class="st">"yes"</span> <span class="sc">&amp;</span> actual <span class="sc">==</span> <span class="st">"yes"</span>) <span class="sc">|</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    (predicted <span class="sc">==</span> <span class="st">"no"</span> <span class="sc">&amp;</span> actual <span class="sc">==</span> <span class="st">"no"</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>accuracy <span class="ot">&lt;-</span> <span class="fu">nrow</span>(correct_predictions) <span class="sc">/</span> <span class="fu">nrow</span>(compas)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>accuracy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6642903</code></pre>
</div>
</div>
<p>In our case, the accuracy of the COMPAS model is about 0.66, meaning it makes the correct prediction 66% of the time. It’s not particularly high, but it’s better than random guessing (50%).</p>
</section>
<section id="confusion-matrix" class="level2">
<h2 class="anchored" data-anchor-id="confusion-matrix">Confusion Matrix</h2>
<p>Accuracy doesn’t show in what way a model makes mistakes. It treats a <strong>false positive</strong> (predicting someone will reoffend when they won’t) the same as a <strong>false negative</strong> (predicting someone won’t reoffend when they will). In practice, these errors can have very different implications.</p>
<p>Confusion matrix breaks down the types of correct and incorrect predictions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># True Positive: predicted recidivism, actually recidivated</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>TP <span class="ot">&lt;-</span> <span class="fu">sum</span>(compas<span class="sc">$</span>predicted <span class="sc">==</span> <span class="st">"yes"</span> <span class="sc">&amp;</span> compas<span class="sc">$</span>actual <span class="sc">==</span> <span class="st">"yes"</span>)  </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># True Negative: predicted no recidivism, didn't recidivate</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>TN <span class="ot">&lt;-</span> <span class="fu">sum</span>(compas<span class="sc">$</span>predicted <span class="sc">==</span> <span class="st">"no"</span> <span class="sc">&amp;</span> compas<span class="sc">$</span>actual <span class="sc">==</span> <span class="st">"no"</span>)  </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># False Positive: predicted recidivism, didn't recidivate</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>FP <span class="ot">&lt;-</span> <span class="fu">sum</span>(compas<span class="sc">$</span>predicted <span class="sc">==</span> <span class="st">"yes"</span> <span class="sc">&amp;</span> compas<span class="sc">$</span>actual <span class="sc">==</span> <span class="st">"no"</span>)  </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co"># False Negative: predicted no recidivism, actually recidivated</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>FN <span class="ot">&lt;-</span> <span class="fu">sum</span>(compas<span class="sc">$</span>predicted <span class="sc">==</span> <span class="st">"no"</span> <span class="sc">&amp;</span> compas<span class="sc">$</span>actual <span class="sc">==</span> <span class="st">"yes"</span>)  </span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a matrix manually</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(TN, FN, FP, TP),</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>                      <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>,</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>                      <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="at">Prediction =</span> <span class="fu">c</span>(<span class="st">"N"</span>, <span class="st">"P"</span>),</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">Reference =</span> <span class="fu">c</span>(<span class="st">"N"</span>, <span class="st">"P"</span>)))</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>conf_matrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Reference
Prediction    N    P
         N 2647 1356
         P  716 1453</code></pre>
</div>
</div>
<p>This matrix reads:</p>
<pre><code>           Reference (Actual)
Prediction    no     yes
         -----------------
      no  |   TN     FN
      yes |   FP     TP</code></pre>
<p>A perfect classifier would only have non-zero values on it’s main diagonal (TN and TP).</p>
<p>To put this result in our context, in the “Actual No” column, there are (2647+716=3363) people who actually did not reoffend. Among them, 716 were misclassified. In other words, about (716/3363 = 21%) non-reoffenders were flagged as high risk. This is the <strong>False Positive Rate (FPR)</strong>: the proportion of non-reoffenders incorrectly predicted as reoffenders.</p>
</section>
<section id="breaking-it-down-by-racial-groups" class="level2">
<h2 class="anchored" data-anchor-id="breaking-it-down-by-racial-groups">Breaking it down by racial groups</h2>
<p>If we take a closer look and break down the confusion matrix by racial groups, we will see that the model’s errors are not evenly distributed.</p>
<p><a href="https://www.propublica.org/article/how-we-analyzed-the-compas-recidivism-algorithm">The analysis by Propublica</a> has this quote:</p>
<blockquote class="blockquote">
<p>“Black defendants were often predicted to be at a higher risk of recidivism than they actually were. Our analysis found that black defendants who did not recidivate over a two-year period were nearly twice as likely to be misclassified as higher risk compared to their white counterparts”</p>
</blockquote>
<p>This means the <strong>FPR</strong> (predicting someone will reoffend when they won’t) is higher for Black defendants compared to white defendants.</p>
<p>We’ll now reproduce this analysis ourselves.</p>
<p>To make the process easier and reusable, we’ll define a function that generates a confusion matrix for any specified race.</p>
<blockquote class="blockquote">
<p>Note: Writing your own function can be a bit less intuitive, but it works like outlining the entire process using “placeholder” variables. After the process is built, you use the function by providing actual variables as inputs to replace those placeholders.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a function to calculate confusion matrix cells by race</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>confusion_by_race <span class="ot">&lt;-</span> <span class="cf">function</span>(df, race_name) {</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  df_race <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span> <span class="fu">filter</span>(race <span class="sc">==</span> race_name)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  TP <span class="ot">&lt;-</span> <span class="fu">sum</span>(df_race<span class="sc">$</span>predicted <span class="sc">==</span> <span class="st">"yes"</span> <span class="sc">&amp;</span> df_race<span class="sc">$</span>actual <span class="sc">==</span> <span class="st">"yes"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  TN <span class="ot">&lt;-</span> <span class="fu">sum</span>(df_race<span class="sc">$</span>predicted <span class="sc">==</span> <span class="st">"no"</span> <span class="sc">&amp;</span> df_race<span class="sc">$</span>actual <span class="sc">==</span> <span class="st">"no"</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  FP <span class="ot">&lt;-</span> <span class="fu">sum</span>(df_race<span class="sc">$</span>predicted <span class="sc">==</span> <span class="st">"yes"</span> <span class="sc">&amp;</span> df_race<span class="sc">$</span>actual <span class="sc">==</span> <span class="st">"no"</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  FN <span class="ot">&lt;-</span> <span class="fu">sum</span>(df_race<span class="sc">$</span>predicted <span class="sc">==</span> <span class="st">"no"</span> <span class="sc">&amp;</span> df_race<span class="sc">$</span>actual <span class="sc">==</span> <span class="st">"yes"</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">c</span>(<span class="at">TP =</span> TP, <span class="at">TN =</span> TN, <span class="at">FP =</span> FP, <span class="at">FN =</span> FN))</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then calculate the confusion matrix for Black and White population, separately.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove other objects from the workspace to start fresh</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">setdiff</span>(<span class="fu">ls</span>(), <span class="fu">c</span>(<span class="st">"compas"</span>, <span class="st">"confusion_by_race"</span>)))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate for Black affenders</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>b_vals <span class="ot">&lt;-</span> <span class="fu">confusion_by_race</span>(compas, <span class="st">"African-American"</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>b_fpr <span class="ot">&lt;-</span> b_vals[<span class="st">"FP"</span>]<span class="sc">/</span>(b_vals[<span class="st">"FP"</span>]<span class="sc">+</span>b_vals[<span class="st">"TN"</span>])</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate for White affenders</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>w_vals <span class="ot">&lt;-</span> <span class="fu">confusion_by_race</span>(compas, <span class="st">"Caucasian"</span>)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>w_fpr <span class="ot">&lt;-</span> w_vals[<span class="st">"FP"</span>]<span class="sc">/</span>(w_vals[<span class="st">"FP"</span>]<span class="sc">+</span> w_vals[<span class="st">"TN"</span>])</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Print our results</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="fu">str_glue</span>(</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"FPR: </span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Black defendants: {round(b_fpr*100)}% </span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"White defendants: {round(w_fpr*100)}%"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>FPR: 
Black defendants: 31% 
White defendants: 14%</code></pre>
</div>
</div>
<p>This aligns with the Propublic result. Black defendants who did not recidivate over a two-year period were nearly twice as likely to be misclassified as higher risk than their White counterparts.</p>
<p>Propublica has another quote:</p>
<blockquote class="blockquote">
<p>“White defendants were often predicted to be less risky than they were. Our analysis found that white defendants who re-offended within the next two years were mistakenly labeled low risk almost twice as often as black re-offenders”</p>
</blockquote>
<p>This points to another type of model error: <strong>False Negative Rate (FNR)</strong>. It tells us, among all people who actually reoffended (the “Actual Yes” column), how many were missed by the model (predicted as No).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate FNR for Black reaffenders</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>b_fnr <span class="ot">&lt;-</span> b_vals[<span class="st">"FN"</span>]<span class="sc">/</span>(b_vals[<span class="st">"FN"</span>]<span class="sc">+</span>b_vals[<span class="st">"TP"</span>]) </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate for White reaffenders</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>w_fnr <span class="ot">&lt;-</span> w_vals[<span class="st">"FN"</span>]<span class="sc">/</span>(w_vals[<span class="st">"FN"</span>]<span class="sc">+</span> w_vals[<span class="st">"TP"</span>])</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Print our results</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="fu">str_glue</span>(</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"FNR: </span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Black defendants: {round(b_fnr*100)}% </span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"White defendants: {round(w_fnr*100)}%"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>FNR: 
Black defendants: 38% 
White defendants: 61%</code></pre>
</div>
</div>
<p>Similar to Propublica’s result, White defendants are almost twice as likely to be incorrectly classify as low-risk compared to Black defendants.</p>
<p>Such kind of pattern is generally referred to as <strong>disparate impact</strong>: when a decision-making process seems neutral on the surface but still results in unequal outcomes for certain groups. In this case, the COMPAS model tends to over-predict risk for Black defendants and under-predict for White defendants, leading to unequal results.</p>
<p>Does this mean the COMPAS model is simply problematic? To explore this further, let’s try building our own prediction model and see how it performs.</p>
</section>
</section>
<section id="logistic-classification-model" class="level1">
<h1>Logistic classification model</h1>
<p>Logistic regression is a supervised learning method that uses a linear combination of variables to predict the probability of a “yes” outcome. When you turn those probabilities into actual labels like “yes” or “no,” it becomes a classification model. The model is based on a straight-line equation, so the line separating the two classes is also straight.</p>
<section id="variable-selection-notes" class="level2">
<h2 class="anchored" data-anchor-id="variable-selection-notes"><strong>Variable selection notes</strong></h2>
<p>Choosing which variables to include in a model is a critical challenge in algorithmic decision-making. Steif’s book highlights an important tension around using predictors like <code>race</code> and <code>prior_count</code>.</p>
<p>If we include race in a Multiple Linear Regression (MLR), for example, the results table will show the effect of the <code>race</code> variable, which might read: “Being race X increases predicted recidivism by 0.2”. This kind of output is problematic. It means the model will consistently add 0.2 for defendants of race X. In other words, it encodes bias into the predictions.</p>
<p>Even if race is not explicitly included as a predictor, variables like <code>priors_count</code> can still reflect historical biases in policing that are correlated with race, leading algorithms to make consistently less accurate predictions for certain socioeconomic groups. Predictors like this, such as redlining districts, eviction history, etc., should be used with caution.</p>
</section>
<section id="model-building" class="level2">
<h2 class="anchored" data-anchor-id="model-building"><strong>Model Building</strong></h2>
<p>We’ll now repeat the modeling workflow you’ve used in previous sessions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>modeldata <span class="ot">&lt;-</span> compas <span class="sc">|&gt;</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(actual, age, sex, race, c_charge_degree, priors_count, length_of_stay)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">24</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>train_index <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> modeldata<span class="sc">$</span>actual,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">p =</span> <span class="fl">0.7</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">list =</span> <span class="cn">FALSE</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> modeldata[train_index, ]</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>test_data  <span class="ot">&lt;-</span> modeldata[<span class="sc">-</span>train_index, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the <code>train()</code> function, set <code>method = "glm"</code> to specify that we’re using a generalized linear model. <code>family = "binomial"</code> indicates that the outcome variable is binary.</p>
<blockquote class="blockquote">
<p>Note: Model comparison tests (such as ANOVA and AIC) will show that <code>priors_count</code> significantly improves model performance. So given our available predictors, we will include <code>priors_count</code> in our model, while excluding <code>race</code>.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>logit_model <span class="ot">&lt;-</span> <span class="fu">train</span>(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  actual <span class="sc">~</span> . <span class="sc">-</span> race,  <span class="co"># The "-" sign is to remove one specific variable from all (".") predictors.</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> train_data,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"glm"</span>,        </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="our-result" class="level2">
<h2 class="anchored" data-anchor-id="our-result"><strong>Our Result</strong></h2>
<p>Use our trained logistic classification model to predict class labels for the test set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>pred_class <span class="ot">&lt;-</span> <span class="fu">predict</span>(logit_model, <span class="at">newdata =</span> test_data)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co"># take a look at the predicted labels</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>pred_class <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] no  yes yes no  yes no  yes no  no  no 
Levels: no yes</code></pre>
</div>
</div>
<p>After generating these predicted classes, we attach them back to the test set for the subsequent confusion matrix calculation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># attach the predictions to the test data</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>test_pred <span class="ot">&lt;-</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  test_data <span class="sc">|&gt;</span> </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">predicted =</span> pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now reuse our previous function <code>confusion_by_race</code> to calculate error metrics by race:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>b_vals <span class="ot">&lt;-</span> <span class="fu">confusion_by_race</span>(test_pred, <span class="st">"African-American"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>b_fpr <span class="ot">&lt;-</span> b_vals[<span class="st">"FP"</span>] <span class="sc">/</span> (b_vals[<span class="st">"FP"</span>] <span class="sc">+</span> b_vals[<span class="st">"TN"</span>])</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>b_fnr <span class="ot">&lt;-</span> b_vals[<span class="st">"FN"</span>] <span class="sc">/</span> (b_vals[<span class="st">"FN"</span>] <span class="sc">+</span> b_vals[<span class="st">"TP"</span>])</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>b_acc <span class="ot">&lt;-</span> (b_vals[<span class="st">"TP"</span>] <span class="sc">+</span> b_vals[<span class="st">"TN"</span>]) <span class="sc">/</span> <span class="fu">sum</span>(b_vals)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>w_vals <span class="ot">&lt;-</span> <span class="fu">confusion_by_race</span>(test_pred, <span class="st">"Caucasian"</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>w_fpr <span class="ot">&lt;-</span> w_vals[<span class="st">"FP"</span>] <span class="sc">/</span> (w_vals[<span class="st">"FP"</span>] <span class="sc">+</span> w_vals[<span class="st">"TN"</span>])</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>w_fnr <span class="ot">&lt;-</span> w_vals[<span class="st">"FN"</span>] <span class="sc">/</span> (w_vals[<span class="st">"FN"</span>] <span class="sc">+</span> w_vals[<span class="st">"TP"</span>])</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>w_acc <span class="ot">&lt;-</span> (w_vals[<span class="st">"TP"</span>] <span class="sc">+</span> w_vals[<span class="st">"TN"</span>]) <span class="sc">/</span> <span class="fu">sum</span>(w_vals)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="fu">str_glue</span>(</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Black Defendants:</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"  FPR: {round(b_fpr * 100, 1)}%</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"  FNR: {round(b_fnr * 100, 1)}%</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"  Accuracy: {round(b_acc * 100, 1)}%</span><span class="sc">\n\n</span><span class="st">"</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Black Defendants:
FPR: 29.9%
FNR: 32%
Accuracy: 69%</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_glue</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"White Defendants:</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"  FPR: {round(w_fpr * 100, 1)}%</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"  FNR: {round(w_fnr * 100, 1)}%</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"  Accuracy: {round(w_acc * 100, 1)}%</span><span class="sc">\n</span><span class="st">"</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>White Defendants:
FPR: 13.1%
FNR: 57.1%
Accuracy: 69.6%</code></pre>
</div>
</div>
<p>Although our model has slightly better accuracy than COMPAS, it produces very similar results and shows the same level of disparities.</p>
<p>Part of the reason models generate biased result is that they learns from historically biased data. We can’t undo the historical patterns that shaped the data, and we often can’t completely avoid using variables that carry implicit bias, especially when they carry predictive power. Recognizing this challenge is broadly referred to as <strong>fairness-aware modeling</strong>.</p>
<p>But there are still a range of strategies we can apply: understanding the data context, being critical about variables that may act as proxies for protected characteristics, and applying fairness techniques in the decision-making process to correct potential harm. We’ll try to improve our logistic classification model using some of these ideas.</p>
</section>
</section>
<section id="adjust-classification-thresholds" class="level1">
<h1>Adjust Classification Thresholds</h1>
<p>In logistic regression, the model doesn’t directly predict a “yes” or “no” outcome. It predicts a probability between 0 and 1 that an observation belongs to the positive class. A final classification decision still needs to be made. By default, the threshold is set at 0.5, meaning if the predicted probability is greater than 0.5, the case is classified as “yes”, otherwise “no”.</p>
<p>By adding <code>type = "prob"</code> in the <code>predict</code> function, we will get the results of <strong>predicted probabilities</strong> instead of class labels. This lets us adjust the decision threshold, which means, if we lower the decision threshold, the model is more likely to predict “yes”.</p>
<p>Changing the threshold affects how predictions fall into true or false positives and negatives, which in turn impacts error rates and fairness.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This is the probability result</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>pred_probs <span class="ot">&lt;-</span> <span class="fu">predict</span>(logit_model, <span class="at">newdata =</span> test_data, <span class="at">type =</span> <span class="st">"prob"</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># take a look at the predicted probabilities</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>pred_probs <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          no       yes
1  0.7724305 0.2275695
2  0.2048619 0.7951381
3  0.3381370 0.6618630
4  0.6199372 0.3800628
5  0.4953815 0.5046185
6  0.7350560 0.2649440
7  0.4632128 0.5367872
8  0.5938938 0.4061062
9  0.5493853 0.4506147
10 0.5636980 0.4363020</code></pre>
</div>
</div>
<p>Now let’s try to set different classification thresholds for different groups!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Attach pred_probs to the test data</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>test_pred <span class="ot">&lt;-</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  test_data <span class="sc">|&gt;</span> </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred_prob =</span> pred_probs<span class="sc">$</span>yes)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Define separate thresholds we want to use</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>thresholds <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">African_American =</span> <span class="fl">0.6</span>,</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Caucasian =</span> <span class="fl">0.5</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new "predicted" column based on group-specific thresholds.</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a><span class="co"># For African-American and Caucasian individuals, apply separate thresholds.</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a><span class="co"># For all others, use the default threshold of 0.5.</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>test_pred <span class="ot">&lt;-</span> test_pred <span class="sc">|&gt;</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">predicted =</span> <span class="fu">case_when</span>(</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>    race <span class="sc">==</span> <span class="st">"African-American"</span> <span class="sc">&amp;</span> pred_prob <span class="sc">&gt;</span> thresholds<span class="sc">$</span>African_American <span class="sc">~</span> <span class="st">"yes"</span>,</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>    race <span class="sc">==</span> <span class="st">"African-American"</span> <span class="sc">&amp;</span> pred_prob <span class="sc">&lt;=</span> thresholds<span class="sc">$</span>African_American <span class="sc">~</span> <span class="st">"no"</span>,</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>    race <span class="sc">==</span> <span class="st">"Caucasian"</span> <span class="sc">&amp;</span> pred_prob <span class="sc">&gt;</span> thresholds<span class="sc">$</span>Caucasian <span class="sc">~</span> <span class="st">"yes"</span>,</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>    race <span class="sc">==</span> <span class="st">"Caucasian"</span> <span class="sc">&amp;</span> pred_prob <span class="sc">&lt;=</span> thresholds<span class="sc">$</span>Caucasian <span class="sc">~</span> <span class="st">"no"</span>,</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>    pred_prob <span class="sc">&gt;</span> <span class="fl">0.5</span> <span class="sc">~</span> <span class="st">"yes"</span>,</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"no"</span></span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>  ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now that we have applied group-specific thresholds, we can calculate and compare performance metrics again: FPR, FNR and Accuracy, for African-American and Caucasian defendants, separately.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># three metrics, FNR, FPR and Accuracy for both race</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>b_vals <span class="ot">&lt;-</span> <span class="fu">confusion_by_race</span>(test_pred, <span class="st">"African-American"</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>b_fpr <span class="ot">&lt;-</span> b_vals[<span class="st">"FP"</span>] <span class="sc">/</span> (b_vals[<span class="st">"FP"</span>] <span class="sc">+</span> b_vals[<span class="st">"TN"</span>])</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>b_fnr <span class="ot">&lt;-</span> b_vals[<span class="st">"FN"</span>] <span class="sc">/</span> (b_vals[<span class="st">"FN"</span>] <span class="sc">+</span> b_vals[<span class="st">"TP"</span>])</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>b_acc <span class="ot">&lt;-</span> (b_vals[<span class="st">"TP"</span>] <span class="sc">+</span> b_vals[<span class="st">"TN"</span>]) <span class="sc">/</span> <span class="fu">sum</span>(b_vals)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>w_vals <span class="ot">&lt;-</span> <span class="fu">confusion_by_race</span>(test_pred, <span class="st">"Caucasian"</span>)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>w_fpr <span class="ot">&lt;-</span> w_vals[<span class="st">"FP"</span>] <span class="sc">/</span> (w_vals[<span class="st">"FP"</span>] <span class="sc">+</span> w_vals[<span class="st">"TN"</span>])</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>w_fnr <span class="ot">&lt;-</span> w_vals[<span class="st">"FN"</span>] <span class="sc">/</span> (w_vals[<span class="st">"FN"</span>] <span class="sc">+</span> w_vals[<span class="st">"TP"</span>])</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>w_acc <span class="ot">&lt;-</span> (w_vals[<span class="st">"TP"</span>] <span class="sc">+</span> w_vals[<span class="st">"TN"</span>]) <span class="sc">/</span> <span class="fu">sum</span>(w_vals)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="fu">str_glue</span>(</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Black Defendants:</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"  FPR: {round(b_fpr * 100, 1)}%</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"  FNR: {round(b_fnr * 100, 1)}%</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"  Accuracy: {round(b_acc * 100, 1)}%</span><span class="sc">\n\n</span><span class="st">"</span></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Black Defendants:
FPR: 12.4%
FNR: 59.4%
Accuracy: 63.3%</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_glue</span>(</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"White Defendants:</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"  FPR: {round(w_fpr * 100, 1)}%</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"  FNR: {round(w_fnr * 100, 1)}%</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"  Accuracy: {round(w_acc * 100, 1)}%</span><span class="sc">\n</span><span class="st">"</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>White Defendants:
FPR: 13.1%
FNR: 57.1%
Accuracy: 69.6%</code></pre>
</div>
</div>
<p>Today’s analysis is built on <a href="https://urbanspatial.github.io/PublicPolicyAnalytics/people-based-ml-models-algorithmic-fairness.html">Chapter 7</a> of <a href="https://urbanspatial.github.io/PublicPolicyAnalytics/">Public Policy Analysis</a>. In this chapter, the author introduced a few guildlines for <strong>an “equity threshold”</strong>,</p>
<ul>
<li>Minimize differences in False Positive Rates (FPR) and False Negative Rates (FNR) between racial groups, while keeping both rates relatively low.</li>
<li>Minimize differences in Accuracy rates between racial groups, while keeping the overall Accuracy high.</li>
</ul>
<p>How would you interpret our new results? Would you consider this a better and more equitable model, or maybe there is more room for improvement?</p>
</section>
<section id="lab-report" class="level1">
<h1>Lab Report</h1>
<p>You’ve seen how changing the decision threshold affects fairness metrics. Previously, we tested one pair of thresholds (0.6 for Black defendants and 0.5 for White defendants). But that was just one possibility. Are there other threshold pairs that might lead to even better fairness or overall performance? How to find them?</p>
<p>Your goal is to <strong>explore multiple possible threshold combinations</strong> to see whether some produce better fairness, better accuracy, or a better balance of both. There is no perfect solution: changing thresholds will always involve trade-offs. Your job is to think like a data scientist who has to explain these trade-offs to stakeholders.</p>
<section id="your-task" class="level2">
<h2 class="anchored" data-anchor-id="your-task"><strong>Your Task</strong></h2>
<ol type="1">
<li><strong>Design your approach.</strong> Decide what racial groups/performance metrics you want to focus on and which threshold values you want to try. For threshold values, you can:</li>
</ol>
<ul>
<li><p>Pick several threshold pairs based on intuition, or</p></li>
<li><p>Use a more systematic approach such as sensitivity analysis by testing a series of thresholds (e.g., 0.1 to 1.0) for both groups.</p>
<p>Your goal here is simply to propose an exploration strategy.</p></li>
</ul>
<ol start="2" type="1">
<li><p><strong>Run your analysis.</strong><br>
For each pair, apply your thresholds, calculate metrics such as FPR, FNR, or Accuracy for both racial groups. You can reuse any part of our code to do this more efficiently.</p></li>
<li><p><strong>Communicate your findings.</strong><br>
Use either tables or visualizations to show how your metrics change. You can simply put together a table to compare metrics across threshold pairs. Or you can choose to use line plots, bar charts, or <a href="https://r-graph-gallery.com/79-levelplot-with-ggplot2.html">heatmap</a>.</p></li>
<li><p><strong>Reflect and recommend.</strong><br>
<strong>Choose</strong> <strong>a recommended threshold pair</strong> <strong>based on your analysis</strong>. Please include a short write-up to explain what you recommend and why, any trade-offs involved and how you’d explain your results to a general audience.</p></li>
</ol>
<p>There’s no perfect answer. This is about exploring, reasoning, and practicing fairness-aware modeling in action.</p>
<p>Please include all your work in a <strong>Quarto document</strong> and submit your <strong>Rendered HTML file</strong> to Canvas by <strong>9am, Wednesday, Nov 26</strong>.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Made with R and <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>