<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-11-04">

<title>ML Model Selection with  – Applied Data Science for Cities</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-f3c2ea88cadbcfb37ba28ffa2c97cfc1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Applied Data Science for Cities</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../labs/index.html"> 
<span class="menu-text">Labs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../resource.html"> 
<span class="menu-text">Resource</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data-processing" id="toc-data-processing" class="nav-link" data-scroll-target="#data-processing">Data Processing</a>
  <ul class="collapse">
  <li><a href="#read-in-the-data" id="toc-read-in-the-data" class="nav-link" data-scroll-target="#read-in-the-data">Read in the data</a></li>
  <li><a href="#get-to-know-the-variables" id="toc-get-to-know-the-variables" class="nav-link" data-scroll-target="#get-to-know-the-variables"><strong>Get to know the variables</strong></a>
  <ul class="collapse">
  <li><a href="#categorical-variables" id="toc-categorical-variables" class="nav-link" data-scroll-target="#categorical-variables">Categorical variables</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#essentials-of-a-linear-model" id="toc-essentials-of-a-linear-model" class="nav-link" data-scroll-target="#essentials-of-a-linear-model">Essentials of a Linear Model</a>
  <ul class="collapse">
  <li><a href="#linear-model-interpretation" id="toc-linear-model-interpretation" class="nav-link" data-scroll-target="#linear-model-interpretation">Linear model interpretation</a>
  <ul class="collapse">
  <li><a href="#coefficients-effect-size" id="toc-coefficients-effect-size" class="nav-link" data-scroll-target="#coefficients-effect-size">Coefficients: effect size</a></li>
  <li><a href="#statistic-values-significance" id="toc-statistic-values-significance" class="nav-link" data-scroll-target="#statistic-values-significance">Statistic values: <strong>significance</strong></a></li>
  <li><a href="#model-performance" id="toc-model-performance" class="nav-link" data-scroll-target="#model-performance"><strong>Model performance</strong></a></li>
  </ul></li>
  </ul></li>
  <li><a href="#moving-to-machine-learning" id="toc-moving-to-machine-learning" class="nav-link" data-scroll-target="#moving-to-machine-learning">Moving to Machine Learning</a>
  <ul class="collapse">
  <li><a href="#machine-learning-workflow" id="toc-machine-learning-workflow" class="nav-link" data-scroll-target="#machine-learning-workflow"><strong>Machine learning workflow</strong></a></li>
  <li><a href="#a-regularized-linear-model" id="toc-a-regularized-linear-model" class="nav-link" data-scroll-target="#a-regularized-linear-model"><strong>A regularized linear model</strong></a></li>
  <li><a href="#tree-based-models" id="toc-tree-based-models" class="nav-link" data-scroll-target="#tree-based-models">Tree-based models</a></li>
  </ul></li>
  <li><a href="#model-summary" id="toc-model-summary" class="nav-link" data-scroll-target="#model-summary">Model Summary</a></li>
  <li><a href="#lab-report" id="toc-lab-report" class="nav-link" data-scroll-target="#lab-report">Lab Report</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ML Model Selection with <img src="../img/Rlogo.png" class="img-fluid" width="60"></h1>
<p class="subtitle lead"><span style="color:#2C3E50">11.118/11.218 Applied Data Science for Cities</span></p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 4, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>From this week on, we’ll start dipping our toes into machine learning. The goal is to explore it as a way to <strong>make predictions</strong>: using what a computer has learned from existing data to make guesses about new data.</p>
<p>Today, as a big-picture look at the machine learning process, we’ll build and compare a few different models to see how each one makes different predictions based on the different rules it has learned.</p>
<p>Our exercise today is built on the example in <a href="https://urbanspatial.github.io/PublicPolicyAnalytics/intro-to-geospatial-machine-learning-part-1.html">Chapter 3</a> from Ken Steif’s book <a href="https://urbanspatial.github.io/PublicPolicyAnalytics/">Policy Policy Analytics</a>, which uses the Boston housing dataset to predict housing prices. The book is a great resource for connecting machine learning with urban studies. If you have time, it’s well worth reading other chapters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-processing" class="level1">
<h1>Data Processing</h1>
<section id="read-in-the-data" class="level2">
<h2 class="anchored" data-anchor-id="read-in-the-data">Read in the data</h2>
<p>We’ll be working with the CSV dataset containing sale prices and housing characteristics for homes sold in Boston between August 2015 and August 2016.</p>
<p>Here is the <a href="https://canvas.mit.edu/courses/33012/files/5804712/download?download_frd=1">data download link</a>.</p>
<p>The data used in this tutorial is a subset of the original larger dataset of <a href="https://data.boston.gov/dataset/property-assessment">Boston property assessment</a>. You can explore the full <a href="https://data.boston.gov/dataset/property-assessment/resource/dbdc1bd8-60af-4913-a788-5f91cb68541b">data dictionary here</a>.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>boston &lt;- read_csv("data/boston_house_price.csv")</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>A few notes:</p>
<ul>
<li>The <code>SalePrice</code> variable is the target we want to predict.</li>
<li>Other columns describe building characteristics such as square footage, number of floors, and number of bedrooms.</li>
<li>Some variables are numeric (<code>dbl</code>), while others are categorical (<code>chr</code> or <code>fct</code>).</li>
</ul>
</section>
<section id="get-to-know-the-variables" class="level2">
<h2 class="anchored" data-anchor-id="get-to-know-the-variables"><strong>Get to know the variables</strong></h2>
<p>Before feeding any data into a model, we need to understand and clean it. Every dataset is different, but there are some key steps you can consider:</p>
<ol type="1">
<li><p><strong>Understand data structure:</strong> <code>glimpse()</code>, <code>str()</code> are useful to get to know the details of variables we are dealing with. <strong>Numeric and categorical variables</strong> require different interpretations in a model later on so this is something to keep in mind. We will also see in our case, <code>parcel_no</code> is just an identifier and is not useful for predicting price.</p></li>
<li><p><strong>Handle missing values.</strong> <code>colSums(is.na(...))</code>, <code>plot_missing()</code> can help identify which variables have missing values and how many. Missing value will not help in learning patterns, and analysts can deal with them in different ways (drop, fill, or flag) depending on variable contexts.</p></li>
<li><p><strong>Look at distributions.</strong> This is an important step (especially before fitting a regression model) because it helps guide feature selection and transformation. We will take a closer look at how these distributions show up in different types of variables:</p>
<h3 id="continuous-variables" class="anchored">Continuous variables</h3></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>boston <span class="sc">|&gt;</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SalePrice, PricePerSq, LivingArea, </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>         GROSS_AREA, NUM_FLOORS, R_BDRMS) <span class="sc">|&gt;</span> </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab8_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><code>pairs()</code> is a base R function, it creates a pairwise scatter plot matrix, which lets you visually examine the relationships between multiple numeric variables at once. In the graph, we usually look for the following:</p>
<ol type="1">
<li><p><strong>How each predictor relates to the outcome</strong> (<code>SalePrice</code> as Y-axis): On the top row, if you see an upward trend (a roughly linear increase with <code>SalePrice</code>), that predictor is likely to be a strong predictor of price.</p></li>
<li><p><strong>Relationships between predictors:</strong> Look for predictors that are highly correlated with each other (a sign of <em>multicollinearity</em>). For instance, <code>LivingArea</code> and <code>GrossArea</code> may appear nearly linear in their scatterplot. If you calculate the <a href="https://www.statstutor.ac.uk/resources/uploaded/pearsons.pdf">Pearson correlation</a>, it’s about 0.94. This means they contain overlapping information.</p>
<ul>
<li>Depending on the modeling method, multicollinearity may or may not be a serious concern. It causes issues for linear models, but not for many others such as tree-based models. But it’s always worth checking.</li>
</ul></li>
<li><p><strong>Pattens, outliers and clusters.</strong> These visual cues in pairwise plots help you decide whether a linear model is appropriate, and whether certain data points might influence your results. For example:</p>
<ul>
<li><p>The variable <code>PricePerSq</code> may look odd with a bunch of y values lining up at x=0. <code>PricePerSq</code> here is a derived variable, calculated as <code>SalePrice / LivingArea</code>. Since it’s directly related to the outcome, it should not be used as a predictor of <code>SalePrice</code>.</p></li>
<li><p>You’ll also notice outliers especially for luxury homes that have extremely high sale prices. This should match what you would see in the histogram of <code>SalePrice</code>. A log transform of such variables would improve model fit for linear models.</p></li>
</ul></li>
</ol>
<section id="categorical-variables" class="level3">
<h3 class="anchored" data-anchor-id="categorical-variables">Categorical variables</h3>
<p>You can make scatterplots with categorical variables (i.e., by including them in a <code>pairs()</code> plot), but the results often look less informative, because points will just line up vertically at two or three x-values.</p>
<p>A better approach for visually checking categorical variables is to compare the average outcome across categories. For example, what is the median <code>Saleprice</code> for each category of <code>Style</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>boston <span class="sc">|&gt;</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SalePrice, OWN_OCC, Style, R_BLDG_STY, R_ROOF_TYP, LU) <span class="sc">|&gt;</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>SalePrice, <span class="at">names_to =</span> <span class="st">"Variable"</span>, <span class="at">values_to =</span> <span class="st">"Value"</span>) <span class="sc">|&gt;</span>  </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Variable, Value) <span class="sc">|&gt;</span> </span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">median_price =</span> <span class="fu">median</span>(SalePrice, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">x =</span> Value, <span class="at">y =</span> median_price),<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> Variable, <span class="at">scales =</span> <span class="st">"free_x"</span>) <span class="sc">+</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Median Sale Price"</span>, <span class="at">x =</span> <span class="st">"Category"</span>, <span class="at">title =</span> <span class="st">"Mean SalePrice by Categorical Variables"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab8_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>When examining categorical variables, we’re not looking for a linear trend, because the categories don’t have a natural order or numeric spacing. Instead, we focus on two main things:</p>
<ol type="1">
<li><p><strong>Differences between groups</strong>. We want to know if the groups differ meaningfully in the outcome variable. If all groups have similar average sale prices, it means the variable doesn’t explain much of the variation in price and is likely a weak predictor. In our case, <code>OWN_OCC</code> seems to have little impact on sale price.</p></li>
<li><p><strong>Rare or problematic groups</strong>. Just like with missing values in numeric variables, rare groups can cause problems in modeling. For example, if we look at the <code>Style</code> variable, we might see a category labeled “Unknown” and it only appears twice in the dataset. Such categories don’t offer enough data to reliably estimate their effect, may introduce noise, and usually need to be removed or combined.</p></li>
<li><p><strong>The meaning of the variables.</strong> For example, <code>R_BLDG_STY</code> is the same thing as <code>Style</code> (just the abbreviations), so it should be removed.</p></li>
</ol>
</section>
</section>
</section>
<section id="essentials-of-a-linear-model" class="level1">
<h1>Essentials of a Linear Model</h1>
<p>We have found a few flags. Let’s first remove a few variables that look irrelevant, then try to fit a Multiple Linear Regression model to see how things look.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>modeldata <span class="ot">&lt;-</span> boston <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(Parcel_No, PricePerSq, GROSS_AREA, R_TOTAL_RM, </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>            R_BLDG_STY, OWN_OCC, Latitude, Longitude)) <span class="sc">|&gt;</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Style <span class="sc">!=</span> <span class="st">"Unknown"</span>) </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>lm_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> modeldata, </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>               SalePrice <span class="sc">~</span> .) <span class="co"># This means using all (.) variables to predict SalePrice</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SalePrice ~ ., data = modeldata)

Residuals:
     Min       1Q   Median       3Q      Max 
-1342169  -138321   -10138   111453  2159243 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        -775973.61  581976.00  -1.333 0.182629    
LivingArea             152.55      16.58   9.201  &lt; 2e-16 ***
StyleColonial      -133117.91   38059.29  -3.498 0.000484 ***
StyleConventional     6530.67   46164.44   0.141 0.887522    
StyleDecker         118762.75   61376.47   1.935 0.053186 .  
StyleOther           75638.93   40447.32   1.870 0.061677 .  
StyleRow_End        227922.13   57592.00   3.958 7.94e-05 ***
StyleRow_Middle     437323.28   58293.60   7.502 1.09e-13 ***
StyleSemi_Det        47152.64   55234.37   0.854 0.393422    
StyleTwo_Fam_Stack  104717.89   54368.57   1.926 0.054290 .  
StyleVictorian     -325292.50   86931.20  -3.742 0.000190 ***
NUM_FLOORS          267640.25   29318.11   9.129  &lt; 2e-16 ***
R_BDRMS             -30455.31    6947.73  -4.383 1.25e-05 ***
R_FULL_BTH          166502.78   16378.56  10.166  &lt; 2e-16 ***
R_HALF_BTH           45764.23   16276.88   2.812 0.004996 ** 
R_KITCH              -5633.29   60579.66  -0.093 0.925924    
R_FPLACE            158822.56   12169.22  13.051  &lt; 2e-16 ***
LUE                 186551.63  370695.90   0.503 0.614867    
LUR1                551233.13  436911.97   1.262 0.207275    
LUR2                256802.56  428071.44   0.600 0.548663    
LUR3                -34729.69  427508.60  -0.081 0.935264    
LUR4               -882391.07  366737.22  -2.406 0.016250 *  
LURL                520149.44  323389.54   1.608 0.107959    
R_ROOF_TYPG         142059.19   31961.21   4.445 9.47e-06 ***
R_ROOF_TYPH         134394.67   37488.74   3.585 0.000348 ***
R_ROOF_TYPL         159753.84   56277.56   2.839 0.004593 ** 
R_ROOF_TYPM         215319.44   41253.43   5.219 2.06e-07 ***
R_ROOF_TYPS         286046.42  152228.93   1.879 0.060438 .  
R_ROOF_TYPU        1021891.32  392031.07   2.607 0.009237 ** 
YR_BUILT              -149.53     103.84  -1.440 0.150088    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 296000 on 1450 degrees of freedom
Multiple R-squared:  0.5911,    Adjusted R-squared:  0.5829 
F-statistic: 72.28 on 29 and 1450 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<section id="linear-model-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="linear-model-interpretation">Linear model interpretation</h2>
<section id="coefficients-effect-size" class="level3">
<h3 class="anchored" data-anchor-id="coefficients-effect-size">Coefficients: effect size</h3>
<p>The <strong><code>Estimate</code></strong> tell us how each predictor is associated with <code>SalePrice</code>, assuming all other variables are held constant. The sign of the values (+ or -) tell you the direction of the relationship.</p>
<blockquote class="blockquote">
<p>i.e.&nbsp;if <code>LivingArea</code> go up by 1 square feet, the house price tends to increase by about $152.55, <strong>keeping all other factors the same</strong>.</p>
</blockquote>
<p>The <strong><code>Standard Error</code></strong> is about how certain we are about the estimate, smaller values mean more confidence.</p>
<blockquote class="blockquote">
<p>i.e.&nbsp;if you ran your regression many times, the estimate (e.g., $152.55) for <code>LivingArea</code> would vary, on average, by $16.58 above or below that value.</p>
</blockquote>
<ul>
<li>Note to revisit: Then we might see a few issues: <code>R_BDRM</code> is <em>negatively associated</em> with housing price, which doesn’t make intuitive sense. This relates back to the multicollinearity issue we’ve spotted. When two predictors relate to each other, the model struggles to disentangle their individual effects.</li>
</ul>
<p>For categorical variables, <code>estimate</code> shows how much the outcome differs from <em>one</em> <em>reference category</em>.</p>
<blockquote class="blockquote">
<p>i.e.&nbsp;<code>Style</code> includes 11 types of housing style, R will pick one (“Cape”, in this case) as the baseline. If the coefficient for <code>"Colonial"</code> is -133,117, it means homes with the <code>"Colonial"</code> style are predicted to cost $133,117 less than <code>"Cape"</code> style homes, holding everything else constant (i.e.&nbsp;same location, sq.ft., etc.).</p>
</blockquote>
</section>
<section id="statistic-values-significance" class="level3">
<h3 class="anchored" data-anchor-id="statistic-values-significance">Statistic values: <strong>significance</strong></h3>
<p><code>t-statistics</code> and <code>p-value</code> measure the extent to which a coefficient is “statistically significant”, in other words, whether the relationship we see between that predictor and the outcome is likely to be real, or could have happened just by random chance.</p>
<p>The higher the t-statistics (and the lower the p-value), the more significant the predictor.</p>
<ul>
<li>Note to revisit: For a variable like <code>Style</code>, some categories are significant while others are not. Does this mean the variable as a whole is useful?</li>
</ul>
</section>
<section id="model-performance" class="level3">
<h3 class="anchored" data-anchor-id="model-performance"><strong>Model performance</strong></h3>
<p>Model performance means how well our regression model fits the data or how useful it is for making predictions. We have several key metrics to evaluate this:</p>
<p>The <strong>coefficient of determination (R²)</strong> tells us the proportion of variance in the outcome that is explained by the predictors, <em>ranging from 0 (no explanatory power) to 1 (perfect fit).</em> For multiple linear regression, look for the Adjusted R2. In our example, it’s ~0.583, meaning this model explain 58.3% of the total variance in the outcome.</p>
<p>The <strong>Root Mean Squared Error (RMSE)</strong> measures the average size of the model’s prediction errors, or how far predicted values are from the actual value. It’s not directly given in the model summary, but can be retrieved:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>(<span class="fu">residuals</span>(lm_model)<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 292937.6</code></pre>
</div>
</div>
<p>With that, we can see our linear model explains ~58.3% of the variation in sale prices. On average, data points have an average error of $292,937. The model is decent, but not great.</p>
<hr>
<p>We’ve made several notes above about issues like collinearity, flipping coefficients, and how variables can influence one another in multiple regression. Explaining all of these properly would take us deeper into statistical studies. For those of you with a background in statistics, you can further explore tools such as:</p>
<ul>
<li>VIF (Variance Inflation Factor) to detect and remove variables with high collinearity, or</li>
<li>ANOVA tests to decide whether including a variable improves model fit.</li>
</ul>
<p><strong>But we’ll part our ways here.</strong> These issues become less critical in many machine learning models, which are designed to handle complex, overlapping, and nonlinear relationships among variables more naturally.</p>
</section>
</section>
</section>
<section id="moving-to-machine-learning" class="level1">
<h1>Moving to Machine Learning</h1>
<p>Traditional statistical methods focus more on <strong>explaining the relationships between variables</strong>, such as whether and two what extent one factor affects another. Machine learning, on the other hand, <strong>focuses more on prediction</strong>: using what the model has learned (any kind of relationship) to make the best guess for new, unseen data.</p>
<p>The two metrics we looked at earlier (R² and RMSE) showed how well the model fit all the data we gave it. They were based on residuals. But they have not yet told us how the model will perform on new data that it hasn’t used before.</p>
<p>To test model performance on unseen data, we need to:</p>
<ol type="1">
<li><p><strong>Evaluate model performance on a new dataset.</strong> In machine learning, we usually split the data into a <strong>training set</strong> and <strong>a test set</strong> for this purpose. We train the model on one portion of the data, and test it on the rest to see how well it generalizes.</p></li>
<li><p><strong>Calculate</strong> <strong>RMSE</strong> <strong>on the test data</strong>. Find the difference between predicted values and true values in the test set. The lower the test RMSE, the better the model’s predictive accuracy.</p></li>
</ol>
<section id="machine-learning-workflow" class="level2">
<h2 class="anchored" data-anchor-id="machine-learning-workflow"><strong>Machine learning workflow</strong></h2>
<p>I will go through a full modeling workflow using the <code>caret</code> package. We’ll probably repeat this workflow several times in upcoming sessions. The code won’t change much because <code>caret</code> lets you build many models (<code>lm</code>, <code>glmnet</code>, <code>rf</code>, <code>svm</code>, <code>xgbTree</code>, etc.) using a consistent syntax.</p>
<p><strong>Step 1:</strong> Data Preprocessing</p>
<p>Based on the EDA of your specific dataset, common tasks can include:</p>
<ul>
<li>Feature selection: removing redundant or irrelevant variables to simplify the model and reduce noise.</li>
<li>Handling missing values: by dropping incomplete records or imputing them with estimated values.</li>
<li>Handling extreme values: by removing outliers, or transforming the variables.</li>
<li>Standardizing data: helpful for some algorithms (though not always required if you want coefficients to stay interpretable).</li>
</ul>
<p>In our case, we’ll use the same prepared dataset we used for the multiple linear regression model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>modeldata <span class="ot">&lt;-</span> boston <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(Parcel_No, PricePerSq, GROSS_AREA, R_TOTAL_RM, </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>            R_BLDG_STY, OWN_OCC, Latitude, Longitude)) <span class="sc">|&gt;</span> </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Style <span class="sc">!=</span> <span class="st">"Unknown"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Step 2:</strong> Split data into training and testing sets</p>
<p>This involves first applying <code>createDataPartition</code> to generate row indices for the training set, then using those row indices to isolate the two subsets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set a random seed to make results reproducible. Without this, R would randomly split the data differently each time you run it.</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># This can be any number, but has to stay the same for all models</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">24</span>)  </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate row indices for the training set</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>train_index <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> modeldata<span class="sc">$</span>SalePrice, <span class="co"># Stratify by SalePrice to keep a similar price distribution in both training and test sets — prevents uneven splits.</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">p =</span> <span class="fl">0.7</span>,                 <span class="co"># we want 70% of the data in the training set.</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">list =</span> <span class="cn">FALSE</span>             <span class="co"># makes sure the output is a vector, not a list, so it's easier to use for indexing.</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Isolate the two subsets</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> modeldata[ train_index,]</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>test_data  <span class="ot">&lt;-</span> modeldata[<span class="sc">-</span>train_index,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Step 3:</strong> Build the model</p>
<p>This is the place where you can swap out the model by simply changing the argument for <code>method=</code> , such as linear regression (<code>"lm"</code>), random forest (<code>"rf"</code>), elastic net (<code>"glmnet"</code>), XGBoost (<code>"xgbTree"</code>), etc.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>lm_model <span class="ot">&lt;-</span> <span class="fu">train</span>(</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  SalePrice <span class="sc">~</span> .,                </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> train_data,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"lm"</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Step 4:</strong> Evaluate Model Accuracy Using RMSE</p>
<p>Now we evaluate how well our model performs on unseen data, that’s what the test set is for.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use predict() to generate predicted sale prices for the test set.</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_model, <span class="at">newdata =</span> test_data) </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># compare those predictions to the actual sale prices using RMSE</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>lm_result <span class="ot">&lt;-</span> <span class="fu">RMSE</span>(pred, test_data<span class="sc">$</span>SalePrice)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>lm_result</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 300800.5</code></pre>
</div>
</div>
<p><code>RMSE</code> is calculated by compare the predicted and actual values in the test data, square them, find the mean, then take the square root. If doing it by hand, it will be like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>((test_data<span class="sc">$</span>SalePrice <span class="sc">-</span> pred)<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 300800.5</code></pre>
</div>
</div>
<p>Note: Still remember the train RMSE we worked out before? It was $292.937. It’s normal and expected that test errors are higher than train errors because the test data is new, the model should be making more mistakes on it.</p>
</section>
<section id="a-regularized-linear-model" class="level2">
<h2 class="anchored" data-anchor-id="a-regularized-linear-model"><strong>A regularized linear model</strong></h2>
<p>It might seem like a good idea to include as many variables as possible in our linear model, but that’s not always the best approach. When we include too many predictors, the model can start to overfit, meaning it fits the training data too closely and ends up capturing random noise rather than meaningful patterns.</p>
<p>Regularization, in its broad sense, is a way to keep models simpler and more generalizable. For linear models, regularization helps the model to “selectively use” only the strong predictors.</p>
<p>There are two common types of <em>linear model</em> regularization: <strong>Ridge regression</strong> shrinks the coefficients of less important variables. <strong>LASSO regression</strong> shrinks some coefficients all the way to zero, effectively dropping those variables from the model. But all you need to do is to change input to the argument <code>method = "glmnet"</code>.</p>
<p>We’ll continue using the same training and test sets as before, so the code below starts directly from the model-building step.</p>
<blockquote class="blockquote">
<p>However, you’ll notice a few key differences compared to the linear regression model:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>trControl = trainControl(method = "cv", number = 5)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>tuneLength = 3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>These two lines tell caret to perform 5-fold cross-validation and try 3 different tuning values for the regularization parameter. What does that mean, we’ll talk more about parameter tuning next time.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>preProcess = c("center", "scale")</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This step standardizes the data because LASSO and Ridge are sensitive to the scale of predictors.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set a random seed</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">24</span>)  </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a new model</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>glmnet_model <span class="ot">&lt;-</span> <span class="fu">train</span>(</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  SalePrice <span class="sc">~</span> ., </span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> train_data,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"glmnet"</span>,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">trControl =</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">5</span>),</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">tuneLength =</span> <span class="dv">3</span>,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(glmnet_model, <span class="at">newdata =</span> test_data) </span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate test RMSE</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>glmnet_result <span class="ot">&lt;-</span> <span class="fu">RMSE</span>(pred, test_data<span class="sc">$</span>SalePrice)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>glmnet_result</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 301857.7</code></pre>
</div>
</div>
</section>
<section id="tree-based-models" class="level2">
<h2 class="anchored" data-anchor-id="tree-based-models">Tree-based models</h2>
<p>So far we have been working with linear models, but oftentimes data just doesn’t fit a straight line (or a flat plane, if we’re in a space with many variables). Real-world relationships can be nonlinear, irregular that a linear model can’t easily capture.</p>
<p>We will introduce <strong>Random Forest</strong> model next time, but it is one of the machine learning models that do not assume a relationship between predictors and the outcome (non-linear model), and do not rely on a fixed number of parameters (non-parametric model). The model learns the structure from the data itself.</p>
<p>Here is how we change the workflow to building a random forest model. Aside from the parameter tuning part that we will address more, the change you need to make is <code>method = "rf"</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set a random seed</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">24</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a new model</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>rf_model <span class="ot">&lt;-</span> <span class="fu">train</span>(</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  SalePrice <span class="sc">~</span> .,        </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> train_data,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"rf"</span>,        </span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">trControl =</span> <span class="fu">trainControl</span>(<span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">5</span>),</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">tuneLength =</span> <span class="dv">5</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(rf_model, <span class="at">newdata =</span> test_data) </span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate test RMSE</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>rf_result <span class="ot">&lt;-</span> <span class="fu">RMSE</span>(pred, test_data<span class="sc">$</span>SalePrice)</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>rf_result</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 276192.4</code></pre>
</div>
</div>
</section>
</section>
<section id="model-summary" class="level1">
<h1>Model Summary</h1>
<p><strong>Here’s a summary of our model results.</strong> We tried a multiple linear model, a regularized linear model, and a Random Forest model. Their RMSE values differ, with the more flexible, nonlinear Random Forest achieving the lowest RMSE (so far).</p>
<blockquote class="blockquote">
<p>Note: One reason the non-linear model performs better here is that <code>SalePrice</code> is skewed and contain outliers, which makes it hard for straight line relationship to fit well. But this is less of an issue for non-linear, non-parametric models.</p>
<p>Note: In this example our multiple linear and regularized linear models perform almost the same, which means, a typical linear model generalizes fine (not overfitting much). Regularization didn’t help much, but it didn’t really hurt either.</p>
</blockquote>
<p>In machine learning, we usually test multiple models to find the one with the best prediction accuracy, which is at the core of this field.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>Model Type</th>
<th>RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Multiple linear regression</td>
<td>300,800.5</td>
</tr>
<tr class="even">
<td>Regularized linear regression</td>
<td>301,857.7</td>
</tr>
<tr class="odd">
<td>Random Forest</td>
<td>276,192.4</td>
</tr>
</tbody>
</table>
<p>As you’ve likely noticed, when we used different models, details like <code>trainControl</code>, <code>preprocess</code> changed. The <code>caret</code> package supports over 230 machine learning algorithms. Each model comes with its own set of hyperparameters that need to be tuned. We’ll explore those in more detail in next s</p>
</section>
<section id="lab-report" class="level1">
<h1>Lab Report</h1>
<p>The <a href="https://www.kaggle.com/datasets/shashanknecrothapa/ames-housing-dataset">Ames Housing dataset</a> was compiled by Dean De Cock for use in data science education. It’s also a popular dataset in the <a href="https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/overview">Kaggle</a> community. You can find many prediction projects based on it, where people demostrate different modeling approaches and techniques.</p>
<p>For practice, we’ll <strong>use the <code>caret</code> package to build models for predicting housing prices using the Ames Housing dataset.</strong> Don’t worry about building a perfect model. The goal is only to walk through the process and get familiar with how it works.</p>
<p><strong>Explore the data:</strong></p>
<ul>
<li>Take a closer look at the dataset and choose a subset of variables you’d like to work with (or use all of them, if you prefer).</li>
<li>Perform exploratory data analysis (EDA) to understand patterns, identify missing values, and decide if you want to remove or treat any variables before putting into models.</li>
<li>Briefly note your reasoning for major data cleaning or transformation steps.</li>
</ul>
<p><strong>Modeling:</strong></p>
<ul>
<li>Fit three different models of your choice.</li>
<li>Compute and compare their test RMSE values to evaluate prediction performance.</li>
</ul>
<p><strong>Summarize your results:</strong></p>
<ul>
<li>Create a summary table comparing the RMSE results from the three models.</li>
</ul>
<p>Please include your code as well as anything you want to note in your report, such as how you prepared the data, selected variables and models, and any data issues or challenges you encountered.</p>
<p>Please include all your work in a <strong>Quarto document</strong> and submit your <strong>Rendered HTML file</strong> to Canvas by <strong>9am, Wednesday, Nov 12.</strong></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Made with R and <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>